// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')
const { generaterandomEmail } = require('../functions/helpers')

describe('again', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('again', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 1228, height: 1033 })
    await driver.findElement(By.css(".modal-cookie-button")).click()
    await driver.findElement(By.css(".btn-primary")).click()
    await driver.findElement(By.css(".btn-custom:nth-child(3)")).click()
    await driver.findElement(By.css(".btn-primary")).click()
    await driver.findElement(By.css(".btn-secondary")).click()
    await driver.findElement(By.css(".btn-custom")).click()
    {
      const element = await driver.findElement(By.css(".btn-custom"))
    //   await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".btn-primary")).click()
    await driver.findElement(By.css(".btn-primary")).click()
    await driver.findElement(By.css(".btn-primary")).click()
    await driver.executeScript("window.scrollTo(0,0)")
    await driver.findElement(By.css(".btn-primary")).click()
    await driver.findElement(By.css(".btn-custom")).click()
    await driver.executeScript("window.scrollTo(0,0)")
    await driver.findElement(By.css(".btn-primary")).click()
    await driver.findElement(By.css(".input-outline")).click()
    await driver.findElement(By.css(".input-outline")).sendKeys(generaterandomEmail())
    await driver.findElement(By.css(".input-outline")).sendKeys(Key.ENTER)
    await driver.findElement(By.css(".btn-custom > .icon-custom")).click()
    await driver.findElement(By.css(".inputs-wrapper:nth-child(1) .pincode-input-text:nth-child(1)")).click()
    await driver.findElement(By.css(".inputs-wrapper:nth-child(1) .pincode-input-text:nth-child(1)")).sendKeys("1")
    await driver.findElement(By.css(".inputs-wrapper:nth-child(1) .pincode-input-text:nth-child(2)")).click()
    await driver.findElement(By.css(".inputs-wrapper:nth-child(1) .pincode-input-text:nth-child(2)")).sendKeys("2")
    await driver.findElement(By.css(".inputs-wrapper:nth-child(1) .pincode-input-text:nth-child(3)")).click()
    await driver.findElement(By.css(".inputs-wrapper:nth-child(1) .pincode-input-text:nth-child(3)")).sendKeys("3")
    await driver.findElement(By.css(".inputs-wrapper:nth-child(1) .pincode-input-text:nth-child(4)")).click()
    await driver.findElement(By.css(".inputs-wrapper:nth-child(1) .pincode-input-text:nth-child(4)")).sendKeys("4")
    await driver.findElement(By.css(".inputs-wrapper:nth-child(1) .pincode-input-text:nth-child(5)")).click()
    await driver.findElement(By.css(".inputs-wrapper:nth-child(1) .pincode-input-text:nth-child(5)")).sendKeys("5")
    await driver.findElement(By.css(".inputs-wrapper:nth-child(1) .pincode-input-text:nth-child(6)")).click()
    await driver.findElement(By.css(".inputs-wrapper:nth-child(1) .pincode-input-text:nth-child(6)")).sendKeys("6")

    await driver.findElement(By.css(".inputs-wrapper:nth-child(2) .pincode-input-text:nth-child(1)")).click()
    await driver.findElement(By.css(".inputs-wrapper:nth-child(2) .pincode-input-text:nth-child(1)")).sendKeys("1")
    await driver.findElement(By.css(".inputs-wrapper:nth-child(2) .pincode-input-text:nth-child(2)")).click()
    await driver.findElement(By.css(".inputs-wrapper:nth-child(2) .pincode-input-text:nth-child(2)")).sendKeys("2")
    await driver.findElement(By.css(".inputs-wrapper:nth-child(2) .pincode-input-text:nth-child(3)")).click()
    await driver.findElement(By.css(".inputs-wrapper:nth-child(2) .pincode-input-text:nth-child(3)")).sendKeys("3")
    await driver.findElement(By.css(".inputs-wrapper:nth-child(2) .pincode-input-text:nth-child(4)")).click()
    await driver.findElement(By.css(".inputs-wrapper:nth-child(2) .pincode-input-text:nth-child(4)")).sendKeys("4")
    await driver.findElement(By.css(".inputs-wrapper:nth-child(2) .pincode-input-text:nth-child(5)")).click()
    await driver.findElement(By.css(".inputs-wrapper:nth-child(2) .pincode-input-text:nth-child(5)")).sendKeys("5")
    await driver.findElement(By.css(".inputs-wrapper:nth-child(2) .pincode-input-text:nth-child(6)")).click()
    await driver.findElement(By.css(".inputs-wrapper:nth-child(2) .pincode-input-text:nth-child(6)")).sendKeys("6")

    await driver.findElement(By.css(".btn-primary")).click()

    {
        const element = await driver.findElement(By.css(".btn-primary"))
    }
    await driver.findElement(By.css(".btn-primary")).click()


    // {
    //     const element = await driver.findElement(By.css("div"))
    // }
  })
})